# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Contentful Jekyll Single Space Example
email: master@contentful.com
description: > # this means to ignore newlines until "baseurl:"
  Single Space Example using Jekyll and Contentful
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jvorak
github_username:  jvorak

  # Build settings
markdown: kramdown

contentful:
  spaces:
    - links:
        space: 5ii8ejp5xdya
        access_token: 72410257d7355ffccb33519a3851e5cdaea7719b2095f70a65c2c36515dc0653
